[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { branch = "main", ref = "9c09cc151d39c6630f6873fdf1ea12f9752df484", version = "0.13.0", git = "https://github.com/risc0/risc0" }

[package.metadata.risc0]
methods = ["guest"]
